// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Diplom.DOMAIN.NewModels
{
    public partial class Persons
    {
        public Persons()
        {
            Audios = new HashSet<Audios>();
            Images = new HashSet<Images>();
            Texts = new HashSet<Texts>();
            UserActions = new HashSet<UserActions>();
            Videos = new HashSet<Videos>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }
        public int LocationId { get; set; }
        public int KindOfActivityId { get; set; }
        public DateTime? BornDate { get; set; }
        public DateTime? DeathDate { get; set; }

        public virtual KindOfActivities KindOfActivity { get; set; }
        public virtual Locations Location { get; set; }
        public virtual ICollection<Audios> Audios { get; set; }
        public virtual ICollection<Images> Images { get; set; }
        public virtual ICollection<Texts> Texts { get; set; }
        public virtual ICollection<UserActions> UserActions { get; set; }
        public virtual ICollection<Videos> Videos { get; set; }
    }
}