// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Diplom.DOMAIN.NewModels
{
    public partial class UserActions
    {
        public int Id { get; set; }
        public int? Estimate { get; set; }
        public int? UserId { get; set; }
        public int? PersonId { get; set; }

        public virtual Persons Person { get; set; }
        public virtual Users User { get; set; }
    }
}