// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Diplom.DOMAIN.NewModels
{
    public partial class Users
    {
        public Users()
        {
            UserActions = new HashSet<UserActions>();
        }

        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public DateTime BirthDay { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }

        public virtual ICollection<UserActions> UserActions { get; set; }
    }
}